import assert from 'node:assert/strict';
import { clamp, smoothstep, randomGenerator, noise2, terrainHeight, seasonalState, riverX } from '../src/math.js';
let tests = 0;
const check = (name, fn) => { fn(); tests++; console.log('PASS:', name); };
check('clamp boundaries', () => { assert.equal(clamp(-1,0,1),0); assert.equal(clamp(2,0,1),1); });
check('smoothstep endpoints and midpoint', () => { assert.equal(smoothstep(0,1,0),0); assert.equal(smoothstep(0,1,1),1); assert.equal(smoothstep(0,1,.5),.5); });
check('deterministic random generator', () => { const a=randomGenerator(17),b=randomGenerator(17); for(let i=0;i<100;i++) assert.equal(a(),b()); });
check('random values remain in [0,1)', () => { const r=randomGenerator(23); for(let i=0;i<10000;i++) { const n=r(); assert.ok(n>=0&&n<1); } });
check('noise values and determinism', () => { for(let i=0;i<100;i++) { const n=noise2(i*.13,-i*.2); assert.ok(n>=0&&n<=1); assert.equal(n,noise2(i*.13,-i*.2)); } });
check('river center is lower than water surface', () => { for(let z=-25;z<=25;z+=.5) assert.ok(terrainHeight(riverX(z),z)<.04); });
check('land heights are finite', () => { for(let x=-27;x<=27;x++) for(let z=-27;z<=27;z++) assert.ok(Number.isFinite(terrainHeight(x,z))); });
check('spring and summer have full leaf coverage', () => { assert.equal(seasonalState(0).coverage,1); assert.equal(seasonalState(1).coverage,1); });
check('sakura blossom intensity peaks in spring', () => { assert.equal(seasonalState(0).spring,1); assert.equal(seasonalState(1).spring,0); assert.ok(seasonalState(.5).spring>0); });
check('sakura petals fall during mid spring only', () => { assert.ok(seasonalState(.5).springPetals>.9); assert.equal(seasonalState(1).springPetals,0); assert.equal(seasonalState(2).springPetals,0); });
check('winter loses leaves and enables snow', () => { const s=seasonalState(3); assert.equal(s.winter,1); assert.ok(Math.abs(s.coverage-.065)<1e-10); });
check('autumn has the strongest falling-leaf density', () => { assert.equal(seasonalState(2).fall,1); assert.equal(seasonalState(2).leafFall,1); assert.ok(seasonalState(2).leafFall > seasonalState(0).leafFall); assert.ok(seasonalState(2).leafFall > seasonalState(1).leafFall); assert.ok(seasonalState(2).leafFall > seasonalState(3).leafFall); });
check('falling foliage exists in every season', () => { assert.equal(seasonalState(0).leafFall,.18); assert.equal(seasonalState(1).leafFall,.10); assert.equal(seasonalState(3).leafFall,.20); });
check('season wraparound', () => { assert.equal(seasonalState(4).phase,0); assert.equal(seasonalState(-1).phase,3); });
check('all seasonal values remain bounded', () => { for(let p=-8;p<=8;p+=.003) { const s=seasonalState(p); for(const k of ['winter','fall','leafFall','spring','springPetals','coverage']) assert.ok(s[k]>=0&&s[k]<=1); } });
console.log(`\n${tests} checks passed.`);
